name: Deploy to FTP

on:
  push:
    branches:
      - main # The branch to which the workflow reacts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Adapt this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --configuration production

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          ftp-server: "ftp://{{ secrets.FTP_USERNAME }}@mathias-kohler.de"
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "dist/videoflix-frontend" # file to upload
          server-dir: "/videoflix.mathias-kohler.de" # path to ftp-server
