name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main # The branch to which the workflow reacts

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Adapt this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --configuration production

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "ftp://w01e658d.kasserver.com"
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "dist/videoflix-frontend/" # file to upload
          server-dir: "/videoflix.mathias-kohler.de/" # path to ftp-server
